4/22/2022 2:47:22 PM
GenerateURL
------------------------------
System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at HBL_MLDV_APP.Repository.LoginRepository.<GetLoginData>d__1.MoveNext() in E:\Naveel\GIT_PROJECTS\HBL_MLDV_APP\HBL_MLDV_APP\Repository\LoginRepository.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at HBL_MLDV_APP.Controllers.LoginController.<GenerateURL>d__3.MoveNext() in E:\Naveel\GIT_PROJECTS\HBL_MLDV_APP\HBL_MLDV_APP\Controllers\LoginController.cs:line 108
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

------------------------------
